[package]
name = "api"
version = "0.1.0"
edition = "2021"

[dependencies]
askama = { version = "*" }
axum = { version = "*" }
axum-login = { version = "*" }
password-auth = { version = "*" }
serde = { version = "*", features = ["derive"] }
sqlx = { version = "*", features = ["mysql", "runtime-tokio"] }
thiserror = { version = "*" }
tokio = { version = "*", features = ["rt-multi-thread"] }
tower-sessions-sqlx-store = { version = "*", features = ["mysql"] }
tracing = { version = "*" }
tracing-subscriber = { version = "*" }
